//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClases.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Usuario
    {
        public int IdUsuario { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Estado { get; set; }
        public int IdPerfil { get; set; }
    
        public virtual T_Perfil T_Perfil { get; set; }
    }
}
